server:
  port: 8888 # [1]

spring:
  application:
    name: config-server # [2]
  profiles:
    active: native # [3]
  cloud:
    config:
      server:
        native:
          # [4] Path to config repo
          search-locations: "file:///C:/Users/DAT/OneDrive - ut.edu.vn/Documents/Desktop/New folder (2)/EV-Charging-Station-Management-System/backend/services/config-repo"

eureka:
  client:
    service-url:
      # [5] Use environment variable for Docker compatibility
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true